#!/bin/sh
set -e

# prefer user supplied CFLAGS, but default to our PHP_CFLAGS
: ${CFLAGS:=$PHP_CFLAGS}
: ${CPPFLAGS:=$PHP_CPPFLAGS}
: ${LDFLAGS:=$PHP_LDFLAGS}
export CFLAGS CPPFLAGS LDFLAGS

usage() {
	echo "usage: $0 ext-name [configure flags]"
	echo "   ie: $0 apcu --enable-apcu-spinlocks"
	echo "       $0 -j5 apcu redis grpc protobuf"
	echo
	echo 'if custom ./configure arguments are necessary, see docker-php-pecl-configure'
}

if [ ! -d $tmpDir ]; then
    if [ -e $tmpdir ]; then
        rm -rf $tmpDir
    fi
    mkdir -p $tmpDir
fi

ext="$1"
if [ -z "$ext" ]; then
    usage >&2
    exit 1
fi
shift

pm='unknown'
if [ -e /lib/apk/db/installed ]; then
    pm='apk'
fi

if [ "$pm" = 'apk' ]; then
	if \
		[ -n "$PHPIZE_DEPS" ] \
		&& ! apk info --installed .phpize-deps > /dev/null \
		&& ! apk info --installed .phpize-deps-configure > /dev/null \
	; then
		apk add --no-cache --virtual .phpize-deps-configure $PHPIZE_DEPS
	fi
fi

if command -v dpkg-architecture > /dev/null; then
	gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)"
	set -- --build="$gnuArch" "$@"
fi

if [ ! -z "$http_proxy" ]; then
    pear config-set http_proxy $http_proxy
fi

pecl install --onlyreqdeps --nobuild "$ext"
cd "/tmp/pear/temp/$ext"
phpize
./configure --enable-option-checking=fatal "$@"
