#!/bin/sh
set -e
SRC_DIR=/usr/src
PHP_SRC_DIR=$SRC_DIR/php

usage() {
    echo "usage: $0 COMMAND"
    echo
    echo "Manage php source tarball lifecycle."
    echo
    echo "Commands:"
    echo "   extract  extract php source tarball into directory $PHP_SRC_DIR if not already done."
    echo "   delete   delete extracted php source located into $PHP_SRC_DIR if not already done."
    echo
}

case "$1" in
    extract)
        if [ -f "$PHP_SRC_DIR" ] ; then
            echo "php source tarball already extracted, skipping extract step."
        else
            mkdir -p $SRC_DIR
            tar -Jxf "/$PHP_FILENAME" -C $SRC_DIR
            mv "$PHP_SRC_DIR-$PHP_VERSION" $PHP_SRC_DIR
            echo "php source tarball successfully extracted."
        fi
        ;;
    delete)
        if [ -d "$PHP_SRC_DIR" ] ; then
            rm -rf $PHP_SRC_DIR \
            && echo "php extracted source successfully deleted."
        else
            echo "php extracted source already deleted, skipping delete extracted source step."
        fi
        ;;
    *)
        usage
        exit 1
        ;;
esac
