ENV PHP_EXTRA_CONFIGURE_ARGS --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi {{
    if env.suite | startswith("alpine") | not then
        # https://github.com/docker-library/php/pull/939#issuecomment-730501748
        "--enable-embed"
    end
}}
