#!/bin/bash
set -e

declare -A gpgKeys
gpgKeys=(
	[7.0]='1A4E8B7277C42E53DBA9C7B9BCAA30EA9C0D5763'
	[5.6]='0BD78B5F97500D450838F95DFE857D9A90D90EC1 6E4F6AB321FDC07F2C332E3AC2BF0BC433CFC8B3'
	[5.5]='0B96609E270F565C13292B24C13C70B87267B52D 0BD78B5F97500D450838F95DFE857D9A90D90EC1 F38252826ACD957EF380D39F2F7956BC5DA04B5D'
)
# see http://php.net/downloads.php

cd "$(dirname "$(readlink -f "$BASH_SOURCE")")"

versions=( "$@" )
if [ ${#versions[@]} -eq 0 ]; then
	versions=( */ )
fi
versions=( "${versions[@]%/}" )

jsonSh="$(curl -fsSL 'https://raw.githubusercontent.com/dominictarr/JSON.sh/ed3f9dd285ebd4183934adb54ea5a2fda6b25a98/JSON.sh')"

travisEnv=
for version in "${versions[@]}"; do
	packagesJson="$(curl -fsSL "https://secure.php.net/releases/index.php?json&max=100&version=${version%%.*}" | bash -- <(echo "$jsonSh") -l)"
	fullVersion=
	filename=
	sha256=
	for comp in xz bz2 gz; do
		fullVersion="$(
			echo "$packagesJson" \
				| grep '^\["'"$version"'[."].*,"filename"\].*\.'"$comp"'"' \
				| cut -d'"' -f2 \
				| head -1
		)"
		if [ "$fullVersion" ]; then
			sourceNumber="$(
				echo "$packagesJson" \
					| grep '^\["'"$fullVersion"'","source",.*,"filename"\].*\.'"$comp"'"' \
					| cut -d, -f3
			)"
			filename="$(
				echo "$packagesJson" \
					| grep '^\["'"$fullVersion"'","source",'"$sourceNumber"',"filename"\]' \
					| cut -d$'\t' -f2 | cut -d'"' -f2
			)"
			sha256="$(
				echo "$packagesJson" \
					| grep '^\["'"$fullVersion"'","source",'"$sourceNumber"',"sha256"\]' \
					| cut -d$'\t' -f2 | cut -d'"' -f2
			)"
			break
		fi
	done
	
	if [ -z "$fullVersion" ]; then
		echo >&2 "warning: missing full version for $version; skipping"
		continue
	fi
	
	gpgKey="${gpgKeys[$version]}"
	if [ -z "$gpgKey" ]; then
		echo >&2 "ERROR: missing GPG key fingerprint for $version"
		echo >&2 "  try looking on http://php.net/downloads.php#gpg-$version"
		exit 1
	fi
	
	dockerfiles=()
	
	cp -v Dockerfile-debian.template "$version/Dockerfile"
	cp -v docker-php-ext-* "$version/"
	dockerfiles+=( "$version/Dockerfile" )
	
	if [ -d "$version/alpine" ]; then
		cp -v Dockerfile-alpine.template "$version/alpine/Dockerfile"
		cp -v docker-php-ext-* "$version/alpine/"
		dockerfiles+=( "$version/alpine/Dockerfile" )
	fi
	
	for target in \
		apache \
		fpm fpm/alpine \
		zts zts/alpine \
	; do
		[ -d "$version/$target" ] || continue
		base="$version/Dockerfile"
		variant="${target%%/*}"
		if [ "$target" != "$variant" ]; then
			variantVariant="${target#$variant/}"
			[ -d "$version/$variantVariant" ] || continue
			base="$version/$variantVariant/Dockerfile"
		fi
		echo "Generating $version/$target/Dockerfile from $base + $variant-Dockerfile-block-*"
		awk '
			$1 == "##</autogenerated>##" { ia = 0 }
			!ia { print }
			$1 == "##<autogenerated>##" { ia = 1; ab++; ac = 0 }
			ia { ac++ }
			ia && ac == 1 { system("cat '$variant'-Dockerfile-block-" ab) }
		' "$base" > "$version/$target/Dockerfile"
		cp -v docker-php-ext-* "$version/$target/"
		dockerfiles+=( "$version/$target/Dockerfile" )
	done
	
	if [ -z "$fullVersion" ]; then
		echo >&2 "ERROR: missing $version in $packagesUrl"
		continue
	fi
	
	(
		set -x
		sed -ri '
			s!%%PHP_VERSION%%!'"$fullVersion"'!;
			s!%%PHP_FILENAME%%!'"$filename"'!;
			s!%%PHP_SHA256%%!'"$sha256"'!;
			s!%%GPG_KEYS%%!'"$gpgKey"'!;
		' "${dockerfiles[@]}"
	)
	
	newTravisEnv=
	for dockerfile in "${dockerfiles[@]}"; do
		dir="${dockerfile%Dockerfile}"
		dir="${dir%/}"
		variant="${dir#$version}"
		variant="${variant#/}"
		newTravisEnv+='\n  - VERSION='"$version VARIANT=$variant"
	done
	travisEnv="$newTravisEnv$travisEnv"
done

travis="$(awk -v 'RS=\n\n' '$1 == "env:" { $0 = "env:'"$travisEnv"'" } { printf "%s%s", $0, RS }' .travis.yml)"
echo "$travis" > .travis.yml
