#!/bin/bash
set -e

# Apache gets grumpy about PID files pre-existing
rm -f /var/run/apache2/apache2.pid
sed -i "/^\s*Listen 80/c\Listen $PORT" /etc/apache2/ports.conf
sed -i "/^\s*Listen 80/c\Listen $PORT" /etc/apache2/apache2.conf
sed -i "/^\s*<VirtualHost \*:80>/c\<VirtualHost \*:$PORT>" /etc/apache2/sites-available/000-default.conf

exec apache2 -DFOREGROUND
