#!/bin/bash

sed -i '/^PHP_EXTRA_VERSION/s/"$/-poly"/' configure
sed -i '/^PHP_EXTRA_VERSION/s/"$/-poly"/' configure.ac
sed -i '/^PHP_EXTRA_VERSION/s"$/-poly"/' Makefile
sed -i '/PHP_EXTRA_VERSION/s/""/"-poly"/' main/php_version.h
sed -i '/PHP_VERSION "/s/"$/-poly"/' main/php_version.h

make -j "$(nproc)"
make install
make clean
