#!/bin/bash

./buildconf -force


sed 's/PHP_EXTRA_VERSION=.*/PHP_EXTRA_VERSION=-polyscripted/' configure > configure.polyscripted
yes | cp configure.polyscripted configure

make -j "$(nproc)"
make install
make clean
