#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

sed -i "s|.*admin.*|    'admin' => password_hash('${FILEMANAGER_PASSWORD}',PASSWORD_DEFAULT)|" /var/www/html/filemanager.php

exec "$@"
